function [UOptimal, flag] = iss_optim_fmincon(UStart, Value, StateVars, ...
                                              DeltaFunction, ...
                                              StageReturnFunction, ...
                                              StateLB, StateUB, Conf)

States = Conf.States;
CodingVector = Conf.CodingVector;
DiscountFactor = Conf.DiscountFactor;
UserConstraintFunctionFile = Conf.UserConstraintFunctionFile;
UserConstraintFunction = Conf.UserConstraintFunction;
Options = Conf.Options;
FminconOptions = Conf.FminconOptions;
  
if Options.StochasticProblem
  [UOptimal, ignore, flag] = fmincon('CostStoch',UStart,Options.A, ...
                                     Options.b,Options.Aeq,Options.beq, ...
                                     Options.ControlLB,Options.ControlUB, ...
                                     UserConstraintFunctionFile, ...
                                     FminconOptions, DeltaFunction, ...
                                     StageReturnFunction, ...
                                     UserConstraintFunction, ...
                                     StateLB, ...
                                     Options.StateStepSize,Options.TimeStep, ...
                                     DiscountFactor,size(StateLB, ...
                                                    2), States, ...
                                     CodingVector,StateVars, Value,Conf, ...
                                     Options.Noise, Options.NoiseSteps, ...
                                     Options.NoiseProb, Options.NoisyVars);
else
  [UOptimal, ignore, flag] = fmincon('CostDeter',UStart,Options.A, ...
                                     Options.b,Options.Aeq,Options.beq, ...
                                     Options.ControlLB,Options.ControlUB, ...
                                     UserConstraintFunctionFile, ...
                                     FminconOptions, ...
                                     DeltaFunction, ...
                                     StageReturnFunction, ...
                                     UserConstraintFunction, ...
                                     StateLB, ...
                                     Options.StateStepSize,Options.TimeStep, ...
                                     DiscountFactor,size(StateLB, ...
                                                    2), States, ...
                                     CodingVector,StateVars, Value,Conf);
end