function Options = iss_conf_fmincon(ControlDimension, varargin)
  if nargin > 2 && isstruct(varargin{1})
    Options = optimset(varargin{:});
  else
    Defaults = optimset('DerivativeCheck', 'off', ...
                        'Diagnostics', 'off', ...
                        'DiffMaxChange', 1e-1, ...
                        'DiffMinChange', 1e-8, ...
                        'Display', 'off', ...
                        'LargeScale', 'off', ...
                        'MaxFunEvals', 100 * ControlDimension, ...
                        'MaxIter',400, ...
                        'MaxSQPIter', Inf, ...
                        'OutputFcn', [], ...
                        'TolCon', 1e-6, ...
                        'TolFun', 1e-6, ...
                        'TolX', 1e-6, ...
                        'Algorithm', 'active-set');
      
    Options = optimset(Defaults, varargin{:});
  end
end
