function SelectValDet(StochasticProblem, DeltaFunction, ...
                        StageReturnFunction,StateLB, StateStepSize, ...
                        TimeStep,DiscountFactor,Dimension,States, ...
                        TotalStates,CodingVector,Noise, ...
                        NoiseSteps,NoiseProb,NoisyVars)

if StochasticProblem
    ValDet = @(U) ValDetStoch(DeltaFunction,StageReturnFunction,StateLB,...
        StateStepSize,TimeStep,DiscountFactor,Dimension,States,...
        TotalStates,CodingVector,U,...
        Noise,NoiseSteps,NoiseProb,NoisyVars);
else
    ValDet = @(U) ValDetDeter(DeltaFunction,StageReturnFunction,StateLB,...
        StateStepSize,TimeStep,DiscountFactor,Dimension,States,...
        TotalStates,CodingVector,U);
end % if StochasticProblem

return ValDet;