function Iterations = solve_current(cpus, states, time_step)
  
  state_step = 0.5 / (states - 1);
  
  [OCM, UOptimal, Value, Errors, Iterations] = ...
      iss_solve('delta', 'cost', 0, 0.5, ...
                'StateStepSize', state_step, ...
                'TimeStep', time_step, ...
                'DiscountRate', 0.9, ...
                'MaxFunEvals', 400, ...
                'TolFun', 1e-12, ...
                'PoolSize', cpus, ...
                'StoppingTolerance', 0.0001, ...
                'Debug' , 1);
end