addpath('infsocsol');

delta_fn = 'fisheries_stochastic_both_delta';
cost_fn = 'fisheries_stochastic_both_cost';
state_lb = [60 0.1];
state_ub = [600  1];
opts = {'ControlLB', -0.01, ...
        'ControlUB', 0.01, ...
        'StochasticProblem', 1, ...
        'DiscountRate', 0.1, ...
        'NumberOfSimulations', 5, ...
        'PoolSize', 2, ...
        'UserConstraintFunctionFile', ...
        'fisheries_stochastic_both_constraints', ...
        'StateStepSize', (state_ub - state_lb) / 20};

conf = iss_conf(state_lb, state_ub, opts{:});

save fisheries_stochastic_both_conf.mat delta_fn cost_fn state_lb state_ub opts

ocm = iss_solve(delta_fn, ...
                cost_fn, ...
                state_lb, state_ub, conf);

save fisheries_stochastic_both_ocm.mat ocm