addpath('infsocsol');

delta_fn = 'fisheries_deterministic_2controls_delta';
cost_fn = 'fisheries_deterministic_2controls_cost';
state_lb = [60 0.1];
state_ub = [600  1];
opts = {'ControlLB', {[-0.005 -0.005]}, ...
        'ControlUB', {[0.005 0.005]}, ...
        'ControlDimension', 2, ...
        'DiscountRate', 0.1, ...
        'UserConstraintFunctionFile', ...
        'fisheries_deterministic_2controls_constraints', ...
        'StateStepSize', (state_ub - state_lb) / 20};

conf = iss_conf(state_lb, state_ub, opts{:});

save fisheries_deterministic_2controls_conf.mat delta_fn cost_fn state_lb state_ub opts

ocm = iss_solve(delta_fn, ...
                cost_fn, ...
                state_lb, state_ub, conf);

save fisheries_deterministic_2controls_ocm.mat ocm