addpath infsocsol

Lower = [60, 0.1];
Upper = [600, 1];

StateStepSize =  (Upper - Lower) / 30;
StateLB = Lower - StateStepSize;
StateUB = Upper + StateStepSize;


%% Basic config
Conf = iss_conf(StateLB, StateUB, ...
                'ControlLB', -0.01, ...
                'ControlUB', 0.01, ...
                'DiscountRate', 0.1, ...
                'StateStepSize', StateStepSize, ...
                'UserConstraintFunctionFile', 'fisheries_constraint');


%% Solve and save with reduced discount rate
fprintf('Deterministic\n');
[OCM, UOptimal, Value, Flags] = ...
    iss_solve('fisheries_delta', 'fisheries_cost', ...
              StateLB, StateUB, Conf, ...
              'ProblemFile', 'fisheries');


%% Solve and save stochastic version
fprintf('Stochastic\n');
[OCM, UOptimal, Value, Flags] = ...
    iss_solve('fisheries_delta_stoch', 'fisheries_cost', ...
              StateLB, StateUB, Conf, ...
              'StochasticProblem', 1, ...
              'ProblemFile', 'fisheries_stoch');
